version: 2
root-markers:
  - .git/
tools:
 prettierd-format: &prettierd-format
    format-command: 'prettierd "${INPUT}"'
    format-stdin: true
 eslintd-lint: &eslintd-lint
    lint-command: 'eslint_d -f unix --stdin --stdin-filename=${INPUT}'
    lint-stdin: true
    lint-ignore-exit-code: true

languages:
  typescript:
    - <<: *prettierd-format
    - <<: *eslintd-lint
